# Generated by Django 6.1 on 2026-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('AI/ML', 'artificial intelligence & Machine Learning'), ('DS & Research', 'Data science and research department'), ('HR & manager', 'HUman Resource & Manager'), ('Interns & JEs', 'Interns & Junior Enigneers')], max_length=100, null=True)),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
