# Generated by Django 6.1 on 2026-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('Delayed', 'Delayed')], max_length=15, null=True),
        ),
    ]
