# Generated by Django 6.0.3 on 2026-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
